In [17]:
import numpy as np
inp_len = np.array([17, 12, 11, 11, 10, 16])
xx=sorted(range(len(inp_len)))
yy=range(len(inp_len))


In [12]:
print(xx
    )
print(yy)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63]
range(0, 64)


In [18]:
sort_perm = np.array(sorted(range(len(inp_len)),
        key=lambda k:inp_len[k], reverse=True))

In [19]:
print(sort_perm)

[0 5 1 2 3 4]


In [20]:
new_inp = inp_len[sort_perm]
print(new_inp)

[17 16 12 11 11 10]


In [22]:
x = np.array([22, 24, 62, 28, 63, 27, 42, 60, 41, 61, 13, 14, 25, 53,  0, 23, 29,
        5,  7,  8,  9, 17, 40, 52, 19, 32, 45, 49, 55, 15, 16, 26, 30, 33,
       34, 37, 50, 20, 35, 38, 44, 48, 56, 57, 58,  1, 11, 12, 36, 46, 47,
       51, 54,  2,  3,  4, 39, 43, 59,  6, 10, 18, 31, 21])
y = np.argsort(x)
print(y)

[14 45 53 54 55 17 59 18 19 20 60 46 47 10 11 29 30 21 61 24 37 63  0 15
  1 12 31  5  3 16 32 62 25 33 34 38 48 35 39 56 22  8  6 57 40 26 49 50
 41 27 36 51 23 13 52 28 42 43 44 58  7  9  2  4]


In [26]:
# inp_len=np.array([17, 12, 11, 11, 11, 16, 10, 16, 16, 16, 10, 12, 12, 18, 18, 14, 14,
#        16, 10, 15, 13,  9, 29, 17, 28, 18, 14, 23, 27, 17, 14, 10, 15, 14,
#        14, 13, 12, 14, 13, 11, 16, 20, 23, 11, 13, 15, 12, 12, 13, 15, 14,
#        12, 16, 18, 12, 15, 13, 13, 13, 11, 23, 19, 28, 27])
inp_len=np.array([17, 12, 11, 16, 10, 15, 14, 28, 27])
sort_perm = np.array(sorted(range(len(inp_len)),
     key=lambda k:inp_len[k], reverse=True))
sort_inp_len = inp_len[sort_perm]
sort_perm_inv = np.argsort(sort_perm)

In [27]:
print("inp_len:",inp_len)
print("sort_perm:",sort_perm)
print("sort_inp_len:",sort_inp_len)
print("sort_perm_inv:",sort_perm_inv)

inp_len: [17 12 11 16 10 15 14 28 27]
sort_perm: [7 8 0 3 5 6 1 2 4]
sort_inp_len: [28 27 17 16 15 14 12 11 10]
sort_perm_inv: [2 6 7 3 8 4 5 0 1]


In [35]:
import torch
import torch.nn as nn

In [30]:
sort_inp_len, sort_perm = torch.sort(torch.tensor(inp_len,dtype=torch.long),0,True)
sort_perm_inv = torch.sort(sort_perm)[1]

In [31]:
print("inp_len:",inp_len)
print("sort_perm:",sort_perm)
print("sort_inp_len:",sort_inp_len)
print("sort_perm_inv:",sort_perm_inv)

inp_len: [17 12 11 16 10 15 14 28 27]
sort_perm: tensor([7, 8, 0, 3, 5, 6, 1, 2, 4])
sort_inp_len: tensor([28, 27, 17, 16, 15, 14, 12, 11, 10])
sort_perm_inv: tensor([2, 6, 7, 3, 8, 4, 5, 0, 1])


In [194]:
def run_lstm(lstm,inp,h):
    return lstm(inp,h)
class myLSTM(nn.Module):
    def __init__(self):
        super(myLSTM,self).__init__()
        self.lstm = nn.LSTM(10,20,2)
    def forward(self,X,h):
        #o,h1 = self.lstm(X,h)
        o,h1 = run_lstm(self.lstm,X,h)
        return o,h1
#         input = torch.randn(5, 3, 10)
#         h0 = torch.randn(2, 3, 20)
#         c0 = torch.randn(2, 3, 20)

In [195]:
m = myLSTM()
#m.eval()

input = torch.randn(5, 3, 10)
h0 = torch.randn(2, 3, 20)
c0 = torch.randn(2, 3, 20)
sm = torch.jit.script(m)
#output, (hn, cn) = m(input, (h0, c0))


RuntimeError: 
cannot call a value of type 'Tensor':
  File "<ipython-input-194-d0749d3c2dd8>", line 2
def run_lstm(lstm,inp,h):
    return lstm(inp,h)
           ~~~~ <--- HERE
'run_lstm' is being compiled since it was called from 'myLSTM.forward'
  File "<ipython-input-194-d0749d3c2dd8>", line 9
    def forward(self,X,h):
        #o,h1 = self.lstm(X,h)
        o,h1 = run_lstm(self.lstm,X,h)
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
        return o,h1


In [187]:
print(sm.code)

def forward(self,
    X: Tensor,
    h: Tensor) -> Tuple[Tensor, Tuple[Tensor, Tensor]]:
  o, h1, = (self.lstm).forward__0(X, None, )
  return (o, h1)



In [168]:
rnn = nn.LSTM(10, 20, 2)
input = torch.randn(5, 3, 10)
h0 = torch.randn(2, 3, 20)
c0 = torch.randn(2, 3, 20)
output, (hn, cn) = rnn(input, (h0, c0

In [145]:
srnn = torch.jit.script(rnn)

In [152]:
print(srnn.code)

ModuleAttributeError: 'RecursiveScriptModule' object has no attribute 'code'

In [144]:
print(output.shape,hn.shape,cn.shape)

torch.Size([5, 3, 20]) torch.Size([2, 3, 20]) torch.Size([2, 3, 20])


In [140]:

class MyLstm(nn.Module):
    def __init__(self,N_word,N_h,N_depth):
        super(MyLstm,self).__init__()
        self.lstm = nn.LSTM(input_size=N_word, hidden_size=N_h,
                num_layers=N_depth, batch_first=True,dropout=0.3, bidirectional=True)
    def forward(self,X,X_len):
        y = self.run_lstm(self.lstm,X,X_len)
        return y
    def run_lstm(lstm, inp, inp_len, hidden=None):

        sort_inp_len, sort_perm = torch.sort(torch.tensor(inp_len,dtype=torch.long),0,True)
        sort_perm_inv = torch.sort(sort_perm)[1]
        if inp.is_cuda:
            sort_perm = sort_perm.cuda()#torch.LongTensor(sort_perm).cuda()
            sort_perm_inv = sort_perm_inv.cuda()#torch.LongTensor(sort_perm_inv).cuda()
        lstm_inp = nn.utils.rnn.pack_padded_sequence(inp[sort_perm],
                sort_inp_len, batch_first=True)
        if hidden is None:
            lstm_hidden = None
        else:
            lstm_hidden = (hidden[0][:, sort_perm], hidden[1][:, sort_perm])

        sort_ret_s, sort_ret_h = lstm(lstm_inp, lstm_hidden)
        ret_s = nn.utils.rnn.pad_packed_sequence(
                sort_ret_s, batch_first=True)[0][sort_perm_inv]
        ret_h = (sort_ret_h[0][:, sort_perm_inv], sort_ret_h[1][:, sort_perm_inv])
        return ret_s, ret_h

In [141]:
mym  = MyLstm(50,20,2)
mym.eval()

MyLstm(
  (lstm): LSTM(50, 20, num_layers=2, batch_first=True, dropout=0.3, bidirectional=True)
)

In [138]:

inp = torch.randn(16,10,50)
inp_len = torch.tensor([4,4,3,8,7,5,5,4,6,5,5,5,4,4,7,6])

In [142]:
smym = torch.jit.script(mym)

RuntimeError: 
 method 'forward' is called recursively. Recursive calls are not supported:
  File "<ipython-input-140-474587f9c428>", line 23
            lstm_hidden = (hidden[0][:, sort_perm], hidden[1][:, sort_perm])

        sort_ret_s, sort_ret_h = lstm(lstm_inp, lstm_hidden)
                                 ~~~~ <--- HERE
        ret_s = nn.utils.rnn.pad_packed_sequence(
                sort_ret_s, batch_first=True)[0][sort_perm_inv]
'MyLstm.run_lstm' is being compiled since it was called from 'MyLstm.forward'
  File "<ipython-input-140-474587f9c428>", line 7
    def forward(self,X,X_len):
        y = self.run_lstm(self.lstm,X,X_len)
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
        return y


In [125]:
print(smym.code)

def forward(self,
    X: Tensor) -> Tuple[Tensor, Tuple[Tensor, Tensor]]:
  return (self.lstm).forward__0(X, None, )



In [130]:
out,other = mym(inp,inp_len)
print(out.shape,other[0].shape,other[1].shape)
print(out[0,:2
         ])

torch.Size([16, 10, 40]) torch.Size([2, 16, 20]) torch.Size([2, 16, 20])
tensor([[ 0.0846, -0.0780, -0.0219,  0.0880, -0.1047, -0.0930,  0.0641, -0.0523,
         -0.1587,  0.0564,  0.2142,  0.0840, -0.0957,  0.1275, -0.0363,  0.1238,
          0.0015,  0.0184,  0.0225, -0.0299,  0.1699, -0.1327, -0.2787, -0.0100,
         -0.2845,  0.0827,  0.0078, -0.0608,  0.2274,  0.4734, -0.2501,  0.0372,
          0.0355,  0.1983, -0.1330,  0.0603, -0.1761,  0.1196, -0.1103, -0.1584],
        [ 0.1242,  0.0422, -0.0466, -0.1192, -0.1026, -0.1122, -0.0913,  0.3413,
          0.0699,  0.3929,  0.2307,  0.0378, -0.1444,  0.1688,  0.2335,  0.2014,
          0.0691,  0.0466, -0.0972,  0.0218,  0.0406, -0.2604, -0.2402,  0.0435,
         -0.2202,  0.1708, -0.1229, -0.1110,  0.0514,  0.5196, -0.2351,  0.1442,
          0.1375,  0.1060, -0.1192,  0.1440, -0.3420, -0.0034, -0.0779, -0.1382]],
       grad_fn=<SliceBackward>)


In [131]:
out2,other2 = smym(inp)
print(out2.shape,other2[0].shape,other2[1].shape)
print(out2[0,:2
         ])

torch.Size([16, 10, 40]) torch.Size([2, 16, 20]) torch.Size([2, 16, 20])
tensor([[ 0.0846, -0.0780, -0.0219,  0.0880, -0.1047, -0.0930,  0.0641, -0.0523,
         -0.1587,  0.0564,  0.2142,  0.0840, -0.0957,  0.1275, -0.0363,  0.1238,
          0.0015,  0.0184,  0.0225, -0.0299,  0.1699, -0.1327, -0.2787, -0.0100,
         -0.2845,  0.0827,  0.0078, -0.0608,  0.2274,  0.4734, -0.2501,  0.0372,
          0.0355,  0.1983, -0.1330,  0.0603, -0.1761,  0.1196, -0.1103, -0.1584],
        [ 0.1242,  0.0422, -0.0466, -0.1192, -0.1026, -0.1122, -0.0913,  0.3413,
          0.0699,  0.3929,  0.2307,  0.0378, -0.1444,  0.1688,  0.2335,  0.2014,
          0.0691,  0.0466, -0.0972,  0.0218,  0.0406, -0.2604, -0.2402,  0.0435,
         -0.2202,  0.1708, -0.1229, -0.1110,  0.0514,  0.5196, -0.2351,  0.1442,
          0.1375,  0.1060, -0.1192,  0.1440, -0.3420, -0.0034, -0.0779, -0.1382]],
       grad_fn=<SliceBackward>)
