In [9]:
lt = []
lt.append(2)
print(lt)
lt.append(3)
print(lt)
lt += [4]

print(lt)
ls = lt+5
print(ls)

[2]
[2, 3]
[2, 3, 4]


TypeError: can only concatenate list (not "int") to list

In [2]:
import torch
x = torch.zeros(2,1,3,1,4)
print(x)
print(x.size())

tensor([[[[[0., 0., 0., 0.]],

          [[0., 0., 0., 0.]],

          [[0., 0., 0., 0.]]]],



        [[[[0., 0., 0., 0.]],

          [[0., 0., 0., 0.]],

          [[0., 0., 0., 0.]]]]])
torch.Size([2, 1, 3, 1, 4])


In [5]:
y = torch.squeeze(x,1)
print(y,y.size())

tensor([[[[0., 0., 0., 0.]],

         [[0., 0., 0., 0.]],

         [[0., 0., 0., 0.]]],


        [[[0., 0., 0., 0.]],

         [[0., 0., 0., 0.]],

         [[0., 0., 0., 0.]]]]) torch.Size([2, 3, 1, 4])


In [12]:
a = torch.arange(15).view(5,3).float()
#print(a,a.size()[1])
x = torch.mean(a,dim=0)
y = torch.mean(a,dim=1)
print(x,y)

tensor([6., 7., 8.]) tensor([ 1.,  4.,  7., 10., 13.])


In [13]:
b = a.reshape((-1,))
print(b)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14.])


In [4]:
xx = 7*7*64+3*3*64+3*3*128+3*3*512+512*10
print(xx)
yy = 96*96*3*10
print(yy)

14592
276480


In [9]:
import torch
x = torch.tensor([1,2,3,4])
print(x.size(),x)

torch.Size([4]) tensor([1, 2, 3, 4])


In [7]:
x = x.unsqueeze(0)
print(x.size(),x)


torch.Size([1, 4]) tensor([[1, 2, 3, 4]])


In [10]:
x = x.unsqueeze(1)
print(x.size(),x)

torch.Size([4, 1]) tensor([[1],
        [2],
        [3],
        [4]])


In [11]:
x = x.unsqueeze(1)
print(x.size(),x)

torch.Size([4, 1, 1]) tensor([[[1]],

        [[2]],

        [[3]],

        [[4]]])


In [1]:
import torch
x=torch.randn(3)
print(x,x.size())

tensor([-0.4274, -0.8713,  0.0957]) torch.Size([3])


In [2]:
y=torch.randn((3))
print(y,y.size())

tensor([1.7851, 1.4428, 0.6122]) torch.Size([3])


In [4]:
from torch.autograd import Variable
x=Variable(x,requires_grad=True)
print(x,x.size())

tensor([-0.4274, -0.8713,  0.0957], requires_grad=True) torch.Size([3])


In [5]:
z=x*2
print(z,z.size)

tensor([-0.8548, -1.7425,  0.1914], grad_fn=<MulBackward>) <built-in method size of Tensor object at 0x114d51ee8>


In [6]:
z.backward(torch.FloatTensor([1,0.1,0.01]))
print(x.data,z.data)
print(x.grad,z.grad)

tensor([-0.4274, -0.8713,  0.0957]) tensor([-0.8548, -1.7425,  0.1914])
tensor([2.0000, 0.2000, 0.0200]) None
