In [9]:
import numpy as np
a = np.arange(1,8)
print(a)

[1 2 3 4 5 6 7]


In [10]:
b = np.reshape(a,(-1,1))
print(b)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]


In [12]:
import torch
bx = torch.from_numpy(b)
print(bx.type())

torch.LongTensor


In [16]:
import torch 
from torch.autograd import Variable
x = torch.randn((3))
x = Variable(x,requires_grad=True)
y = x*2
print(y)

tensor([-1.1139,  2.0279,  0.7858])


In [52]:
x.grad.zero_()
y.backward(torch.Tensor([1,.1,.01]))
print(x.grad)

tensor([ 2.0000,  0.2000,  0.0200])


In [53]:
xy = torch.zeros(1)

In [54]:
print(xy)

tensor([ 0.])


In [56]:
y = [[1],[2]]
z = [[1,2]]
t = [1,2]
     
print(y[0],y[1],z[0][0],z[0][1],t[0],t[1])

[1] [2] 1 2 1 2


In [61]:
x1 = torch.randn(2,1)
print(x1)
#print(x1[0].data[0])

tensor([[ 0.5998],
        [ 0.7585]])


In [64]:
print(x1[0].data[0])

tensor(0.5998)
