In [1]:
import tensorflow as tf

In [6]:
na1 = tf.constant([[1.,5.]])
na2 = tf.constant([1.,5.])
na3 = tf.constant([[[1.,5.]]])
print "na1:",na1.shape,",na2:",na2.shape,",na3:",na3.shape
print "na1:",type(na1),"\nna2:",type(na2),"\nna3:",type(na3)

na1: (1, 2) ,na2: (2,) ,na3: (1, 1, 2)
na1: <class 'tensorflow.python.framework.ops.Tensor'> 
na2: <class 'tensorflow.python.framework.ops.Tensor'> 
na3: <class 'tensorflow.python.framework.ops.Tensor'>


In [11]:
matrix1 = tf.constant([[3., 3.]])

# 创建另外一个常量 op, 产生一个 2x1 矩阵.
matrix2 = tf.constant([[2.],[2.]])
product = tf.matmul(matrix1, matrix2)
with tf.Session() as sess:
    result = sess.run(product)
    print product
    print result

Tensor("MatMul_4:0", shape=(1, 1), dtype=float32)
[[ 12.]]


In [15]:
input1 = tf.constant(3.0)
input2 = tf.constant(2.0)
input3 = tf.constant(5.0)
intermed = tf.add(input2, input3)
mul = tf.multiply(input1, intermed)

with tf.Session() as sess:
  result = sess.run([mul, intermed])
  print result

[21.0, 7.0]


In [8]:
x=tf.constant([[1.,2.],
               [3.,4.]])
y=tf.reduce_mean(x)
z=tf.reduce_mean(x,0)
u=tf.reduce_mean(x,1)

In [9]:
with tf.Session() as session:
    result = session.run(y)
    print "y= %s" % result
    result = session.run(z)
    print "z= %s" % result
    result = session.run(u)
    print "u= %s"%result
    

y= 2.5
z= [ 2.  3.]
u= [ 1.5  3.5]


In [28]:
#此处验证矩阵加法，如何让矩阵加一个向量。
import numpy as np
import tensorflow as tf
x = tf.Variable(tf.zeros([2,3],tf.float32))
b = tf.Variable(tf.zeros([3],tf.float32))
y = tf.assign(x,[[2,3,4],[1,2,5]])
b2 = tf.assign(b,[1,-1,1])                
z = y+b2  #此处的加法，将b2【3】的向量分别加到y【2x3】矩阵的每一行上
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    y2= sess.run(y)
    z2 = sess.run(z)
    print "y2=",y2
    print "z2=",z2
r=[[2,3,4],[1,2,5]]
s=[1,-1,1]
t = r+s #此处的加法，是将向量s【3】追加到矩阵r【2x3】的最后，形成一个【3x3】矩阵。
print "t=",t

y2= [[ 2.  3.  4.]
 [ 1.  2.  5.]]
z2= [[ 3.  2.  5.]
 [ 2.  1.  6.]]
t= [[2, 3, 4], [1, 2, 5], 1, -1, 1]


In [40]:

import tensorflow as tf
x = tf.Variable(tf.zeros([2,6],tf.float32))

z= tf.assign(x,[[1,2,3,4,5,6],[7,8,9,10,11,12]])
y = tf.reshape(z,[-1,2,3])
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print "x=",x.eval()
    
    yr = sess.run(y)
    print "yr=",yr

x= [[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]]
yr= [[[  1.   2.   3.]
  [  4.   5.   6.]]

 [[  7.   8.   9.]
  [ 10.  11.  12.]]]


In [1]:
import pandas as pd

In [2]:
s = pd.Series(list('abca'))
s

0    a
1    b
2    c
3    a
dtype: object

In [12]:
t = pd.get_dummies(s)
#type(t)
r = t.values
r

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0]], dtype=uint8)

In [9]:
node1 = tf.constant(3.0, dtype=tf.float32)
node2 = tf.constant(4.0) # also tf.float32 implicitly
print(node1, node2)
sess = tf.Session()
result = sess.run([node1, node2])
print(result)
node3 = tf.add(node1, node2)
print("sess.run(node3):", sess.run(node3))
a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)
adder_node = a + b  # + provides a shortcut for tf.add(a, b)
print(sess.run(adder_node, {a:3, b:4.5}))
print(sess.run(adder_node, {a: [1, 3], b: [2, 4]}))
add_and_triple = adder_node * 3.
print(sess.run(add_and_triple, {a: 3, b: 4.5}))

(<tf.Tensor 'Const_14:0' shape=() dtype=float32>, <tf.Tensor 'Const_15:0' shape=() dtype=float32>)
[3.0, 4.0]
('sess.run(node3):', 7.0)
7.5
[ 3.  7.]
22.5


In [16]:
W = tf.Variable([.3], dtype=tf.float32)
b = tf.Variable([-.3], dtype=tf.float32)
x = tf.placeholder(tf.float32)
init = tf.global_variables_initializer()
sess.run(init)
linear_model = W * x + b
linear_model
print(sess.run(linear_model,{x:[3.14,1,2,3]}))

[ 0.64200008  0.          0.30000001  0.60000002]


In [21]:
zx = tf.constant([[1,1,1],[1,1,1]])
print zx.shape
zy = tf.reduce_sum(zx,1)
zr = sess.run(zy)
print "zy=",zr


(2, 3)
zy= [3 3]


In [30]:
import tensorflow as tf
x = tf.placeholder(tf.float32)
y = tf.placeholder (tf.float32)
W = tf.Variable(.3 , dtype=tf.float32)
b = tf.Variable(-.3,dtype=tf.float32)
vinit = tf.global_variables_initializer()
lm = W*x+b
sq = tf.square(lm - y)
loss = tf.reduce_sum(sq)
optimizer = tf.train.GradientDescentOptimizer(0.01)
train = optimizer.minimize(loss)
sess = tf.Session()
sess.run(vinit)
for i in range(1000):
    sess.run(train,{x:[1,2,3,4],y:[0,-1,-2,-3]})
print(sess.run([W, b]))
#print W,b

[-0.9999969, 0.99999082]


In [36]:
zz = tf.zeros([3])
zz2=tf.zeros([1,3])
zr = sess.run(zz)
zr2=sess.run(zz2)
print "zr=",zr
print "zr2=",zr2


zr= [ 0.  0.  0.]
zr2= [[ 0.  0.  0.]]


In [43]:
import tensorflow as tf
sess = tf.InteractiveSession()
zx2 = tf.constant([1,2,3],shape=[3])
zx3 = tf.random_normal(shape=[3, 3])
print sess.run(zx3)
zx4 = tf.truncated_normal([5, 5, 1, 32], stddev=0.1)
print zx4.eval()

[[-0.30948308 -0.52688724 -0.16754265]
 [-0.40847349 -1.21165311  0.77639049]
 [ 1.18179858 -0.36526814 -1.741045  ]]
[[[[-0.07763758 -0.19292486 -0.01697135  0.04260815 -0.10561567  0.04235503
    -0.10373684  0.10107751  0.09830898  0.06095357  0.00485296  0.07568271
     0.00724091 -0.07585794 -0.04595007  0.02950489 -0.02763073 -0.01654856
     0.09304058 -0.03180665  0.00439753 -0.07705075  0.06384693  0.11988862
     0.00763007  0.09971558 -0.1502797  -0.07892548 -0.04794798  0.05814451
     0.08477338 -0.024729  ]]

  [[-0.07192839  0.00455693  0.03780096 -0.04098595  0.19249912 -0.10610469
     0.14180768  0.08550525 -0.06988584 -0.06329756  0.11106122  0.05853065
     0.04438072 -0.03845915 -0.02621862  0.09460219 -0.10954858  0.01011253
     0.03287388 -0.00164157  0.06429213  0.05903031  0.10408294  0.04855515
     0.06105424 -0.03100383  0.01104861 -0.1872834  -0.07646006  0.03236635
    -0.08718151 -0.00681558]]

  [[ 0.13880114  0.10111462 -0.18542321  0.15676074  0.07650