In [2]:
import torch

In [2]:
x = torch.tensor([3.0,4,5,6])

In [3]:
x

tensor([3., 4., 5., 6.])

In [4]:
l1 = id(x)
print(l1)

140461035209920


In [8]:
X = torch.arange(12,dtype=torch.float32).reshape(3,4)
Y = torch.tensor([[2,5,8,9],[1,7,6,2],[3,5,7,9]])


In [9]:
before=id(Y)
Y=Y+X
before==id(Y)

False

In [4]:
A  = torch.arange(20,dtype = torch.float32).reshape(5,4)
B = A.clone()
print(id(A),id(B))
A,A+B

140292641201024 140292641205120


(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [5]:
x = torch.arange(4,dtype=torch.float32)
x,x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [10]:
z=torch.tensor(6.0)

In [6]:
y = torch.tensor([6.])
y

tensor([6.])

In [7]:
y.item()

6.0

In [12]:
z.item()

6.0

In [13]:
A = torch.arange(20).reshape(5,4)
x = torch.arange(4)
A,x

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]]),
 tensor([0, 1, 2, 3]))

In [14]:
torch.mv(A,x)

tensor([ 14,  38,  62,  86, 110])

In [17]:
torch.matmul(A,x)

tensor([ 14,  38,  62,  86, 110])

In [20]:
B=torch.arange(12).reshape(4,3)
B

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [21]:
torch.mm(A,B)

tensor([[ 42,  48,  54],
        [114, 136, 158],
        [186, 224, 262],
        [258, 312, 366],
        [330, 400, 470]])

In [1]:
import torch

In [2]:
x = 8
print(id(x))

94374029651488


In [3]:
x+=9
print(id(x),x)

94374029651776 17


In [4]:
x = torch.normal(0,1,size=(2,2))

In [5]:
print(id(x))

140560184502080


In [27]:
x+=torch.normal(0,0.01,size=x.shape)
print(id(x))

140560184524992


140560184502080


In [14]:
x= x+torch.normal(0,0.01,size=x.shape)
print(id(x))

140560184524992


In [28]:
y = [8,4]
print(id(y))

140560184590976


In [37]:
y += [1,2]
print(id(y))

140560184590976


In [40]:
num_examples = 1000
w = torch.tensor([-2,3.4])
b = 4.2
X = torch.normal(0,1,(num_examples,len(w)))
y = torch.matmul(X,w)+b
y+=torch.normal(0,0.01,y.shape)
print(y.shape)
print(y.reshape((-1,1)).shape)
print(y.reshape((1,-1)).shape)

torch.Size([1000])
torch.Size([1000, 1])
torch.Size([1, 1000])


In [42]:
x = torch.tensor([[2.],[3.]])

In [43]:
dir(x)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_priority__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__div__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__idiv__',
 '__ifloordiv__',
 '__ilshift__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__long__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pow__',
 '__radd__',
 '__rdiv__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rfloordiv__',
 '__rmul__',
 '__rpow__',
 '__rshift__',
 '__rsub__',
 '__r

In [46]:
print(x.requires_grad_(True))

tensor([[2.],
        [3.]], requires_grad=True)


In [53]:
def f1(*tensors):
    print(tensors)

In [50]:
f1(*(5,8,9))

(5, 8, 9)


In [52]:
def f2(**tensors):
    print(tensors)

In [54]:
f1(*(5,8,9))

(5, 8, 9)


In [60]:
f2(a=5,b=8,c=9)

{'a': 5, 'b': 8, 'c': 9}


In [62]:
f2(**{'a':5,'b':8,'c':9})

{'a': 5, 'b': 8, 'c': 9}


In [63]:
y = torch.tensor([0,2])
y_hat = torch.tensor([[0.1,0.3,0.6],[0.3,0.2,0.5]])

In [64]:
y_hat[[0,1],y]

tensor([0.1000, 0.5000])